{true(X,R,Y) : relation(R)} = 1 :- element(X); element(Y); X != Y.
true(X,eq,X) :- element(X).
:- true(X,R1,Y); true(Y,R2,Z); not true(X,Rout,Z) : table(R1,R2,Rout).
:- possible(X,_,Y); not true(X,R,Y) : possible(X,R,Y).
relation(eq; rev; alt; ret; s; f; ex; exi; i; dis).
table(eq, eq, (eq)).
table(eq, rev, (rev)).
table(eq, alt, (alt)).
table(eq, ret, (ret)).
table(eq, s, (s)).
table(eq, f, (f)).
table(eq, ex, (ex)).
table(eq, exi, (exi)).
table(eq, i, (i)).
table(eq, dis, (dis)).
table(rev, eq, (rev)).
table(rev, rev, (eq)).
table(rev, alt, (ret)).
table(rev, ret, (alt)).
table(rev, s, (exi)).
table(rev, f, (ex)).
table(rev, ex, (f)).
table(rev, exi, (s)).
table(rev, i, (i)).
table(rev, dis, (dis)).
table(alt, eq, (alt)).
table(alt, rev, (ret)).
table(alt, alt, (eq;alt)).
table(alt, ret, (rev;ret)).
table(alt, s, (s)).
table(alt, f, (f)).
table(alt, ex, (ex)).
table(alt, exi, (exi)).
table(alt, i, (i;dis)).
table(alt, dis, (i;dis)).
table(ret, eq, (ret)).
table(ret, rev, (alt)).
table(ret, alt, (rev;ret)).
table(ret, ret, (eq;alt)).
table(ret, s, (exi)).
table(ret, f, (ex)).
table(ret, ex, (f)).
table(ret, exi, (s)).
table(ret, i, (i;dis)).
table(ret, dis, (i;dis)).
table(s, eq, (s)).
table(s, rev, (ex)).
table(s, alt, (s)).
table(s, ret, (ex)).
table(s, s, (eq;alt;s)).
table(s, f, (exi;i;dis)).
table(s, ex, (rev;ret;ex)).
table(s, exi, (f;i;dis)).
table(s, i, (f;exi;i;dis)).
table(s, dis, (f;exi;i;dis)).
table(f, eq, (f)).
table(f, rev, (exi)).
table(f, alt, (f)).
table(f, ret, (exi)).
table(f, s, (ex;i;dis)).
table(f, f, (eq;alt;f)).
table(f, ex, (s;i;dis)).
table(f, exi, (rev;ret;exi)).
table(f, i, (s;ex;i;dis)).
table(f, dis, (s;ex;i;dis)).
table(ex, eq, (ex)).
table(ex, rev, (s)).
table(ex, alt, (ex)).
table(ex, ret, (s)).
table(ex, s, (f;i;dis)).
table(ex, f, (rev;ret;ex)).
table(ex, ex, (exi;i;dis)).
table(ex, exi, (eq;alt;s)).
table(ex, i, (f;exi;i;dis)).
table(ex, dis, (f;exi;i;dis)).
table(exi, eq, (exi)).
table(exi, rev, (f)).
table(exi, alt, (exi)).
table(exi, ret, (f)).
table(exi, s, (rev;ret;exi)).
table(exi, f, (s;i;dis)).
table(exi, ex, (eq;alt;f)).
table(exi, exi, (ex;i;dis)).
table(exi, i, (s;ex;i;dis)).
table(exi, dis, (s;ex;i;dis)).
table(i, eq, (i)).
table(i, rev, (i)).
table(i, alt, (i;dis)).
table(i, ret, (i;dis)).
table(i, s, (f;ex;i;dis)).
table(i, f, (s;exi;i;dis)).
table(i, ex, (s;exi;i;dis)).
table(i, exi, (f;ex;i;dis)).
table(i, i, (eq;rev;alt;ret;s;f;ex;exi;i;dis)).
table(i, dis, (alt;ret;s;f;ex;exi;i;dis)).
table(dis, eq, (dis)).
table(dis, rev, (dis)).
table(dis, alt, (i;dis)).
table(dis, ret, (i;dis)).
table(dis, s, (f;ex;i;dis)).
table(dis, f, (s;exi;i;dis)).
table(dis, ex, (s;exi;i;dis)).
table(dis, exi, (f;ex;i;dis)).
table(dis, i, (alt;ret;s;f;ex;exi;i;dis)).
table(dis, dis, (eq;rev;alt;ret;s;f;ex;exi;i;dis)).
